TouhouLauncher/Views/GameConfigWindow.xaml
Closes #3
Changed color of the buttons in game config on mouse over. (image attached showing one being moused over)
=> Changed the style of the buttons when moused over in game config

.github/workflows/dotnet-core.yml
=> Added .NET Core build action

Test/Test.csproj, TouhouLauncher/TouhouLauncher.csproj
Upgrades the project to .NET 5.0.100.
It's okay if this build fails. The build action is outdated.
Closes #24 
*&lt;Insert here, if relevant...&gt;*
=> Upgraded to .NET 5

TouhouLauncher/ViewModels/GameConfigViewModel.cs, TouhouLauncher/ViewModels/MainViewModel.cs, TouhouLauncher/ViewModels/SettingsViewModel.cs, TouhouLauncher/Views/Pages/SettingsPage.xaml, TouhouLauncher/Views/UserControls/Settings/GameLocationsSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GameLocationsSettings.xaml.cs, TouhouLauncher/Views/UserControls/Settings/GeneralSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GeneralSettings.xaml.cs
Implements settings category page swapping, and adds a second settings category page for testing swapping between the two.
Closes #6
=> Implemented settings category page swapping

TouhouLauncher/ViewModels/HomeViewModel.cs, TouhouLauncher/ViewModels/MainViewModel.cs, TouhouLauncher/ViewModels/SettingsViewModel.cs
Implements use of messaging pattern for communicating between view models.
=> Implemented use of messaging pattern

TouhouLauncher/App.xaml, TouhouLauncher/DependencyLocator.cs, TouhouLauncher/ViewModels/GeneralSettingsViewModel.cs, TouhouLauncher/ViewModels/HomeViewModel.cs, TouhouLauncher/Views/Pages/SettingsPage.xaml, TouhouLauncher/Views/UserControls/Settings/GeneralSettings.xaml
Adds the current general settings to the settings page.
Any changes gets automatically saved and updated in the launcher. 
=> Added content to general settings page

TouhouLauncher.Test/Models/Application/GamePickerListTest.cs, TouhouLauncher.Test/Services/Application/GameCategoryServiceTest.cs, TouhouLauncher/Models/Application/ActiveGameCategory.cs, TouhouLauncher/Models/Application/GameInfo/FanGame.cs, TouhouLauncher/Models/Application/GameInfo/Game.cs, TouhouLauncher/Models/Application/GameInfo/GameCategories.cs, TouhouLauncher/Models/Application/GameInfo/OfficialGame.cs, TouhouLauncher/Models/Application/GamePickerList.cs, TouhouLauncher/Models/Application/Settings/SettingsManager.cs, TouhouLauncher/Services/Application/GameCategoryService.cs, TouhouLauncher/Services/Application/OfficialGamesTemplateService.cs, TouhouLauncher/ViewModels/HomeViewModel.cs
Refactores how game categories work to include fan games as well.
Also changed write permissions on some game properties.
Insert here, if relevant...
=> Refactored how game categories work

TouhouLauncher.Test/Services/Application/LaunchRandomGameServiceTest.cs, TouhouLauncher/AppDependencies.cs, TouhouLauncher/Services/Application/ActivateGameService.cs, TouhouLauncher/Services/Application/LaunchRandomGameService.cs, TouhouLauncher/ViewModels/HomeViewModel.cs
Adds launch random game functionality
Adds tests
=> Implement launch random game

TouhouLauncher/Models/Application/FileBrowserService.cs, TouhouLauncher/ViewModels/GameConfigViewModel.cs, TouhouLauncher/ViewModels/GameLocationsSettingsViewModel.cs
Fixes file browsing bug when clicking cancel makes textbox become empty.
=> Fixed file browsing bug

TouhouLauncher.Test/CommonTestToolsAndData.cs, TouhouLauncher.Test/Models/Application/SettingsAndGamesManagerTest.cs, TouhouLauncher.Test/Models/Infrastructure/Persistence/FileSystem/FileSystemSettingsAndGamesServiceTest.cs, TouhouLauncher/Models/Application/SettingsAndGames.cs, TouhouLauncher/Models/Application/SettingsAndGamesManager.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/YamlTypes/SettingsAndGamesYaml.cs, TouhouLauncher/Models/Infrastructure/YamlSerializerService.cs
Changes order of settings in settings file, and improves YAML serialization.
=> Changed order of settings in settings file, and improved serialization

TouhouLauncher/App.xaml, TouhouLauncher/Views/Pages/SettingsPage.xaml
Redesigned Back button to look like a cross in a circle. Also added tooltip that says "Back".
=> Redesigned back button to look like a cross in a circle

TouhouLauncher.Test/CommonTestToolsAndData.cs, TouhouLauncher.Test/Models/Application/SettingsAndGamesManagerTest.cs, TouhouLauncher.Test/Models/Infrastructure/Persistence/FileSystem/FileSystemSettingsAndGamesServiceTest.cs, TouhouLauncher/Models/Application/FileBrowserService.cs, TouhouLauncher/Models/Application/SettingsAndGames.cs, TouhouLauncher/Models/Application/SettingsAndGamesManager.cs, TouhouLauncher/Models/Application/SettingsInfo/EmulatorSettings.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/YamlTypes/EmulatorSettingsYaml.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/YamlTypes/SettingsAndGamesYaml.cs
Added settings for emulator folder location.
=> Added settings for emulator folder location

TouhouLauncher/Models/Application/LaunchGameService.cs, TouhouLauncher/ViewModels/GameConfigViewModel.cs, TouhouLauncher/ViewModels/GameLocationsSettingsViewModel.cs
Makes browsing for PC-98 games filter on .hdi file type instead of .exe.
=> Made browsing for PC-98 games filter on .hdi file type

TouhouLauncher/AppDependencies.cs, TouhouLauncher/ViewModels/FanGameEditorViewModel.cs, TouhouLauncher/ViewModels/HomeViewModel.cs, TouhouLauncher/ViewModels/SettingsViewModel.cs, TouhouLauncher/Views/GameConfigWindow.xaml, TouhouLauncher/Views/Pages/FanGameEditorPage.xaml, TouhouLauncher/Views/Pages/FanGameEditorPage.xaml.cs, TouhouLauncher/Views/Pages/HomePage.xaml, TouhouLauncher/Views/UserControls/Settings/EmulatorSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GameLocationsSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GeneralSettings.xaml
Adds fan game editor view with navigation, but no business logic.
=> Added fan game editor view with navigation

TouhouLauncher.Test/Models/Application/FanGameEditingServiceTest.cs, TouhouLauncher/Models/Application/FanGameEditingService.cs, TouhouLauncher/ViewModels/FanGameEditorViewModel.cs, TouhouLauncher/Views/Pages/FanGameEditorPage.xaml
Adds button for deleting an existing fan game.
=> Added button for deleting an existing fan game

TouhouLauncher.Test/CommonTestToolsAndData.cs, TouhouLauncher.Test/Models/Application/FanGameEditingServiceTest.cs, TouhouLauncher.Test/Models/Application/GameConfigServiceTest.cs, TouhouLauncher.Test/Models/Application/LaunchRandomGameServiceTest.cs, TouhouLauncher/App.xaml, TouhouLauncher/AppDependencies.cs, TouhouLauncher/Models/Application/FanGameEditingService.cs, TouhouLauncher/Models/Application/GameConfigService.cs, TouhouLauncher/Models/Application/GameInfo/FanGame.cs, TouhouLauncher/Models/Application/GameInfo/Game.cs, TouhouLauncher/Models/Application/GameInfo/OfficialGame.cs, TouhouLauncher/Models/Application/LaunchRandomGameService.cs, TouhouLauncher/Models/Application/OfficialGamesTemplateService.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/YamlTypes/FanGameYaml.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/YamlTypes/OfficialGameYaml.cs, TouhouLauncher/ViewModels/FanGameEditorViewModel.cs, TouhouLauncher/ViewModels/GameConfigViewModel.cs, TouhouLauncher/ViewModels/GamesSettingsViewModel.cs, TouhouLauncher/ViewModels/SettingsViewModel.cs, TouhouLauncher/Views/GameConfigWindow.xaml, TouhouLauncher/Views/Pages/FanGameEditorPage.xaml, TouhouLauncher/Views/Pages/SettingsPage.xaml, TouhouLauncher/Views/UserControls/Settings/EmulatorSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GamesSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GamesSettings.xaml.cs, TouhouLauncher/Views/UserControls/Settings/GeneralSettings.xaml
Adds checkboxes to games for selecting random game.
=> Added checkboxes to games for selecting random game

TouhouLauncher/Models/Application/OfficialGamesTemplateService.cs, TouhouLauncher/ViewModels/EmulatorSettingsViewModel.cs, TouhouLauncher/ViewModels/GameConfigViewModel.cs, TouhouLauncher/ViewModels/GamesSettingsViewModel.cs, TouhouLauncher/Views/GameConfigWindow.xaml, TouhouLauncher/Views/UserControls/Settings/EmulatorSettings.xaml, TouhouLauncher/Views/UserControls/Settings/GamesSettings.xaml
Added links on games and the emulator to external download sources.
The links lead to different pages on https://moriyashrine.org/
=> Added links on games and emulator to external downloads

.github/workflows/dotnet-master.yml, TouhouLauncher.Test/TouhouLauncher.Test.csproj, TouhouLauncher/TouhouLauncher.csproj
=> Migrated projects to .NET 6

.github/workflows/building-and-testing.yml, .github/workflows/create-release-draft.yml, .gitignore, TouhouLauncher/Properties/PublishProfiles/x64.pubxml, TouhouLauncher/Properties/PublishProfiles/x86.pubxml, TouhouLauncher/TouhouLauncher.csproj, TouhouLauncher/ViewModels/SettingsViewModel.cs, TouhouLauncher/Views/Pages/SettingsPage.xaml
Adds GitHub actions release automation and shows version number on the settings page.
=> Mcflyboy/add GitHub actions release automation

.github/workflows/create-release-draft.yml, TouhouLauncher/ViewModels/SettingsViewModel.cs, TouhouLauncher/Views/Pages/SettingsPage.xaml
Makes some fixes on automation and versioning.
=> Some fixes on automation and versioning

.github/workflows/create-release-draft.yml, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/FileAccessService.cs, TouhouLauncher/Models/Infrastructure/Persistence/FileSystem/FileSystemSettingsAndGamesRepository.cs, TouhouLauncher/Properties/PublishProfiles/x64.pubxml, TouhouLauncher/Properties/PublishProfiles/x86.pubxml
Moved settings file to AppData and added spaces to production folder names and zip file names.
=> Moved settings file to AppData and added spaces to prod folder names
